blank_issues_enabled: false
contact_links:
  - name: üí¨ –û–±—Å—É–∂–¥–µ–Ω–∏—è
    url: https://github.com/timokay/GoalFlow/discussions
    about: –ó–∞–¥–∞–≤–∞–π—Ç–µ –≤–æ–ø—Ä–æ—Å—ã –∏ –¥–µ–ª–∏—Ç–µ—Å—å –∏–¥–µ—è–º–∏
  - name: üìñ –î–æ–∫—É–º–µ–Ω—Ç–∞—Ü–∏—è
    url: https://github.com/timokay/GoalFlow#readme
    about: –ü—Ä–æ—á–∏—Ç–∞–π—Ç–µ –¥–æ–∫—É–º–µ–Ω—Ç–∞—Ü–∏—é –ø—Ä–æ–µ–∫—Ç–∞

